# Generated by Django 5.0.4 on 2024-04-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('mileage', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('raw_data', models.JSONField()),
            ],
        ),
    ]
