# Generated by Django 5.0.4 on 2024-04-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobahn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
