# Generated by Django 5.0.4 on 2024-04-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobahn_app', '0002_carlisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
